name: Maxcraft
main: fr.maxcraft.Main
version: 1.0.0
description: Maxcraft
author: Crevebedaine
commands:

  help:
  marker:
  travel:
  mute:
  kick:
  jail:
  ban:
  fine:
  journal:
  invsee:
  enderchest:
  msg:
  r: